// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xopzwbximpioksrnmdyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvcHp3YnhpbXBpb2tzcm5tZHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0OTM3NjYsImV4cCI6MjA2MDA2OTc2Nn0.uHjI8iRr_XflkAbqNxERJMXvL-KyNR4pCGgcpr1FJC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);